/* Auto-generated by genmsg_cpp for file /home/rss-student/RSS-I-group/lab6_msgs/msg/GUIRectMsg.msg */
#ifndef LAB6_MSGS_MESSAGE_GUIRECTMSG_H
#define LAB6_MSGS_MESSAGE_GUIRECTMSG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "lab5_msgs/ColorMsg.h"

namespace lab6_msgs
{
template <class ContainerAllocator>
struct GUIRectMsg_ {
  typedef GUIRectMsg_<ContainerAllocator> Type;

  GUIRectMsg_()
  : c()
  , x(0.0)
  , y(0.0)
  , width(0.0)
  , height(0.0)
  , filled(0)
  {
  }

  GUIRectMsg_(const ContainerAllocator& _alloc)
  : c(_alloc)
  , x(0.0)
  , y(0.0)
  , width(0.0)
  , height(0.0)
  , filled(0)
  {
  }

  typedef  ::lab5_msgs::ColorMsg_<ContainerAllocator>  _c_type;
   ::lab5_msgs::ColorMsg_<ContainerAllocator>  c;

  typedef float _x_type;
  float x;

  typedef float _y_type;
  float y;

  typedef float _width_type;
  float width;

  typedef float _height_type;
  float height;

  typedef int32_t _filled_type;
  int32_t filled;


private:
  static const char* __s_getDataType_() { return "lab6_msgs/GUIRectMsg"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "c0bf17dcdde695b717319df27b23e5f8"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "lab5_msgs/ColorMsg c\n\
float32 x\n\
float32 y\n\
float32 width\n\
float32 height\n\
int32 filled\n\
================================================================================\n\
MSG: lab5_msgs/ColorMsg\n\
int64 r\n\
int64 g\n\
int64 b\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, c);
    ros::serialization::serialize(stream, x);
    ros::serialization::serialize(stream, y);
    ros::serialization::serialize(stream, width);
    ros::serialization::serialize(stream, height);
    ros::serialization::serialize(stream, filled);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, c);
    ros::serialization::deserialize(stream, x);
    ros::serialization::deserialize(stream, y);
    ros::serialization::deserialize(stream, width);
    ros::serialization::deserialize(stream, height);
    ros::serialization::deserialize(stream, filled);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(c);
    size += ros::serialization::serializationLength(x);
    size += ros::serialization::serializationLength(y);
    size += ros::serialization::serializationLength(width);
    size += ros::serialization::serializationLength(height);
    size += ros::serialization::serializationLength(filled);
    return size;
  }

  typedef boost::shared_ptr< ::lab6_msgs::GUIRectMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab6_msgs::GUIRectMsg_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GUIRectMsg
typedef  ::lab6_msgs::GUIRectMsg_<std::allocator<void> > GUIRectMsg;

typedef boost::shared_ptr< ::lab6_msgs::GUIRectMsg> GUIRectMsgPtr;
typedef boost::shared_ptr< ::lab6_msgs::GUIRectMsg const> GUIRectMsgConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::lab6_msgs::GUIRectMsg_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::lab6_msgs::GUIRectMsg_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace lab6_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::lab6_msgs::GUIRectMsg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::lab6_msgs::GUIRectMsg_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::lab6_msgs::GUIRectMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c0bf17dcdde695b717319df27b23e5f8";
  }

  static const char* value(const  ::lab6_msgs::GUIRectMsg_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc0bf17dcdde695b7ULL;
  static const uint64_t static_value2 = 0x17319df27b23e5f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::lab6_msgs::GUIRectMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "lab6_msgs/GUIRectMsg";
  }

  static const char* value(const  ::lab6_msgs::GUIRectMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::lab6_msgs::GUIRectMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "lab5_msgs/ColorMsg c\n\
float32 x\n\
float32 y\n\
float32 width\n\
float32 height\n\
int32 filled\n\
================================================================================\n\
MSG: lab5_msgs/ColorMsg\n\
int64 r\n\
int64 g\n\
int64 b\n\
";
  }

  static const char* value(const  ::lab6_msgs::GUIRectMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::lab6_msgs::GUIRectMsg_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::lab6_msgs::GUIRectMsg_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.c);
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.width);
    stream.next(m.height);
    stream.next(m.filled);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GUIRectMsg_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab6_msgs::GUIRectMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::lab6_msgs::GUIRectMsg_<ContainerAllocator> & v) 
  {
    s << indent << "c: ";
s << std::endl;
    Printer< ::lab5_msgs::ColorMsg_<ContainerAllocator> >::stream(s, indent + "  ", v.c);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    s << indent << "filled: ";
    Printer<int32_t>::stream(s, indent + "  ", v.filled);
  }
};


} // namespace message_operations
} // namespace ros

#endif // LAB6_MSGS_MESSAGE_GUIRECTMSG_H

