"""autogenerated by genmsg_py from GUILineMsg.msg. Do not edit."""
import roslib.message
import struct

import lab5_msgs.msg

class GUILineMsg(roslib.message.Message):
  _md5sum = "5ee858aa33ac4230e8ab893c71e571e8"
  _type = "lab5_msgs/GUILineMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 lineA
float64 lineB
float64 lineC
ColorMsg color
================================================================================
MSG: lab5_msgs/ColorMsg
int64 r
int64 g
int64 b
"""
  __slots__ = ['lineA','lineB','lineC','color']
  _slot_types = ['float64','float64','float64','lab5_msgs/ColorMsg']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       lineA,lineB,lineC,color
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(GUILineMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.lineA is None:
        self.lineA = 0.
      if self.lineB is None:
        self.lineB = 0.
      if self.lineC is None:
        self.lineC = 0.
      if self.color is None:
        self.color = lab5_msgs.msg.ColorMsg()
    else:
      self.lineA = 0.
      self.lineB = 0.
      self.lineC = 0.
      self.color = lab5_msgs.msg.ColorMsg()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_3d3q.pack(_x.lineA, _x.lineB, _x.lineC, _x.color.r, _x.color.g, _x.color.b))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.color is None:
        self.color = lab5_msgs.msg.ColorMsg()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.lineA, _x.lineB, _x.lineC, _x.color.r, _x.color.g, _x.color.b,) = _struct_3d3q.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_3d3q.pack(_x.lineA, _x.lineB, _x.lineC, _x.color.r, _x.color.g, _x.color.b))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.color is None:
        self.color = lab5_msgs.msg.ColorMsg()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.lineA, _x.lineB, _x.lineC, _x.color.r, _x.color.g, _x.color.b,) = _struct_3d3q.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_3d3q = struct.Struct("<3d3q")
