/* Auto-generated by genmsg_cpp for file /home/rss-student/RSS-I-group/Challenge_msgs/msg/GUIStringMessage.msg */
#ifndef CHALLENGE_MSGS_MESSAGE_GUISTRINGMESSAGE_H
#define CHALLENGE_MSGS_MESSAGE_GUISTRINGMESSAGE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "lab5_msgs/ColorMsg.h"

namespace Challenge_msgs
{
template <class ContainerAllocator>
struct GUIStringMessage_ {
  typedef GUIStringMessage_<ContainerAllocator> Type;

  GUIStringMessage_()
  : c()
  , x(0.0)
  , y(0.0)
  , text()
  {
  }

  GUIStringMessage_(const ContainerAllocator& _alloc)
  : c(_alloc)
  , x(0.0)
  , y(0.0)
  , text(_alloc)
  {
  }

  typedef  ::lab5_msgs::ColorMsg_<ContainerAllocator>  _c_type;
   ::lab5_msgs::ColorMsg_<ContainerAllocator>  c;

  typedef float _x_type;
  float x;

  typedef float _y_type;
  float y;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _text_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  text;


private:
  static const char* __s_getDataType_() { return "Challenge_msgs/GUIStringMessage"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "171646c1eb3d834632dc6fe2c47d66aa"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "lab5_msgs/ColorMsg c\n\
float32 x\n\
float32 y\n\
string text\n\
\n\
\n\
================================================================================\n\
MSG: lab5_msgs/ColorMsg\n\
int64 r\n\
int64 g\n\
int64 b\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, c);
    ros::serialization::serialize(stream, x);
    ros::serialization::serialize(stream, y);
    ros::serialization::serialize(stream, text);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, c);
    ros::serialization::deserialize(stream, x);
    ros::serialization::deserialize(stream, y);
    ros::serialization::deserialize(stream, text);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(c);
    size += ros::serialization::serializationLength(x);
    size += ros::serialization::serializationLength(y);
    size += ros::serialization::serializationLength(text);
    return size;
  }

  typedef boost::shared_ptr< ::Challenge_msgs::GUIStringMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Challenge_msgs::GUIStringMessage_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GUIStringMessage
typedef  ::Challenge_msgs::GUIStringMessage_<std::allocator<void> > GUIStringMessage;

typedef boost::shared_ptr< ::Challenge_msgs::GUIStringMessage> GUIStringMessagePtr;
typedef boost::shared_ptr< ::Challenge_msgs::GUIStringMessage const> GUIStringMessageConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::Challenge_msgs::GUIStringMessage_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::Challenge_msgs::GUIStringMessage_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace Challenge_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Challenge_msgs::GUIStringMessage_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Challenge_msgs::GUIStringMessage_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Challenge_msgs::GUIStringMessage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "171646c1eb3d834632dc6fe2c47d66aa";
  }

  static const char* value(const  ::Challenge_msgs::GUIStringMessage_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x171646c1eb3d8346ULL;
  static const uint64_t static_value2 = 0x32dc6fe2c47d66aaULL;
};

template<class ContainerAllocator>
struct DataType< ::Challenge_msgs::GUIStringMessage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Challenge_msgs/GUIStringMessage";
  }

  static const char* value(const  ::Challenge_msgs::GUIStringMessage_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Challenge_msgs::GUIStringMessage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "lab5_msgs/ColorMsg c\n\
float32 x\n\
float32 y\n\
string text\n\
\n\
\n\
================================================================================\n\
MSG: lab5_msgs/ColorMsg\n\
int64 r\n\
int64 g\n\
int64 b\n\
";
  }

  static const char* value(const  ::Challenge_msgs::GUIStringMessage_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Challenge_msgs::GUIStringMessage_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.c);
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.text);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GUIStringMessage_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Challenge_msgs::GUIStringMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::Challenge_msgs::GUIStringMessage_<ContainerAllocator> & v) 
  {
    s << indent << "c: ";
s << std::endl;
    Printer< ::lab5_msgs::ColorMsg_<ContainerAllocator> >::stream(s, indent + "  ", v.c);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.text);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CHALLENGE_MSGS_MESSAGE_GUISTRINGMESSAGE_H

