"""autogenerated by genmsg_py from DigitalStatusMsg.msg. Do not edit."""
import roslib.message
import struct


class DigitalStatusMsg(roslib.message.Message):
  _md5sum = "7a2af7d23e6ef46fbd1d9066e3666f04"
  _type = "rss_msgs/DigitalStatusMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool[8] slow
bool[8] fast
"""
  __slots__ = ['slow','fast']
  _slot_types = ['bool[8]','bool[8]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       slow,fast
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(DigitalStatusMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.slow is None:
        self.slow = [False,False,False,False,False,False,False,False]
      if self.fast is None:
        self.fast = [False,False,False,False,False,False,False,False]
    else:
      self.slow = [False,False,False,False,False,False,False,False]
      self.fast = [False,False,False,False,False,False,False,False]

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      buff.write(_struct_8B.pack(*self.slow))
      buff.write(_struct_8B.pack(*self.fast))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      start = end
      end += 8
      self.slow = _struct_8B.unpack(str[start:end])
      self.slow = map(bool, self.slow)
      start = end
      end += 8
      self.fast = _struct_8B.unpack(str[start:end])
      self.fast = map(bool, self.fast)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      buff.write(self.slow.tostring())
      buff.write(self.fast.tostring())
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      start = end
      end += 8
      self.slow = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=8)
      self.slow = map(bool, self.slow)
      start = end
      end += 8
      self.fast = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=8)
      self.fast = map(bool, self.fast)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_8B = struct.Struct("<8B")
