/* Auto-generated by genmsg_cpp for file /home/rss-student/RSS-I-group/rss_msgs/msg/ArmMsg.msg */
#ifndef RSS_MSGS_MESSAGE_ARMMSG_H
#define RSS_MSGS_MESSAGE_ARMMSG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace rss_msgs
{
template <class ContainerAllocator>
struct ArmMsg_ {
  typedef ArmMsg_<ContainerAllocator> Type;

  ArmMsg_()
  : pwms()
  {
    pwms.assign(0);
  }

  ArmMsg_(const ContainerAllocator& _alloc)
  : pwms()
  {
    pwms.assign(0);
  }

  typedef boost::array<int64_t, 8>  _pwms_type;
  boost::array<int64_t, 8>  pwms;


  ROS_DEPRECATED uint32_t get_pwms_size() const { return (uint32_t)pwms.size(); }
private:
  static const char* __s_getDataType_() { return "rss_msgs/ArmMsg"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "6de3c9cc70fe3f9be077ade811350687"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int64[8] pwms\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, pwms);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, pwms);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(pwms);
    return size;
  }

  typedef boost::shared_ptr< ::rss_msgs::ArmMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rss_msgs::ArmMsg_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ArmMsg
typedef  ::rss_msgs::ArmMsg_<std::allocator<void> > ArmMsg;

typedef boost::shared_ptr< ::rss_msgs::ArmMsg> ArmMsgPtr;
typedef boost::shared_ptr< ::rss_msgs::ArmMsg const> ArmMsgConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::rss_msgs::ArmMsg_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::rss_msgs::ArmMsg_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace rss_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rss_msgs::ArmMsg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rss_msgs::ArmMsg_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rss_msgs::ArmMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6de3c9cc70fe3f9be077ade811350687";
  }

  static const char* value(const  ::rss_msgs::ArmMsg_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6de3c9cc70fe3f9bULL;
  static const uint64_t static_value2 = 0xe077ade811350687ULL;
};

template<class ContainerAllocator>
struct DataType< ::rss_msgs::ArmMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rss_msgs/ArmMsg";
  }

  static const char* value(const  ::rss_msgs::ArmMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rss_msgs::ArmMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64[8] pwms\n\
";
  }

  static const char* value(const  ::rss_msgs::ArmMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::rss_msgs::ArmMsg_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rss_msgs::ArmMsg_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.pwms);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ArmMsg_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rss_msgs::ArmMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::rss_msgs::ArmMsg_<ContainerAllocator> & v) 
  {
    s << indent << "pwms[]" << std::endl;
    for (size_t i = 0; i < v.pwms.size(); ++i)
    {
      s << indent << "  pwms[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.pwms[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // RSS_MSGS_MESSAGE_ARMMSG_H

