/* Auto-generated by genmsg_cpp for file /home/rss-student/RSS-I-group/rss_msgs/msg/DigitalStatusMsg.msg */
#ifndef RSS_MSGS_MESSAGE_DIGITALSTATUSMSG_H
#define RSS_MSGS_MESSAGE_DIGITALSTATUSMSG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace rss_msgs
{
template <class ContainerAllocator>
struct DigitalStatusMsg_ {
  typedef DigitalStatusMsg_<ContainerAllocator> Type;

  DigitalStatusMsg_()
  : slow()
  , fast()
  {
    slow.assign(false);
    fast.assign(false);
  }

  DigitalStatusMsg_(const ContainerAllocator& _alloc)
  : slow()
  , fast()
  {
    slow.assign(false);
    fast.assign(false);
  }

  typedef boost::array<uint8_t, 8>  _slow_type;
  boost::array<uint8_t, 8>  slow;

  typedef boost::array<uint8_t, 8>  _fast_type;
  boost::array<uint8_t, 8>  fast;


  ROS_DEPRECATED uint32_t get_slow_size() const { return (uint32_t)slow.size(); }
  ROS_DEPRECATED uint32_t get_fast_size() const { return (uint32_t)fast.size(); }
private:
  static const char* __s_getDataType_() { return "rss_msgs/DigitalStatusMsg"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "7a2af7d23e6ef46fbd1d9066e3666f04"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "bool[8] slow\n\
bool[8] fast\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, slow);
    ros::serialization::serialize(stream, fast);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, slow);
    ros::serialization::deserialize(stream, fast);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(slow);
    size += ros::serialization::serializationLength(fast);
    return size;
  }

  typedef boost::shared_ptr< ::rss_msgs::DigitalStatusMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rss_msgs::DigitalStatusMsg_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct DigitalStatusMsg
typedef  ::rss_msgs::DigitalStatusMsg_<std::allocator<void> > DigitalStatusMsg;

typedef boost::shared_ptr< ::rss_msgs::DigitalStatusMsg> DigitalStatusMsgPtr;
typedef boost::shared_ptr< ::rss_msgs::DigitalStatusMsg const> DigitalStatusMsgConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::rss_msgs::DigitalStatusMsg_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::rss_msgs::DigitalStatusMsg_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace rss_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rss_msgs::DigitalStatusMsg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rss_msgs::DigitalStatusMsg_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rss_msgs::DigitalStatusMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7a2af7d23e6ef46fbd1d9066e3666f04";
  }

  static const char* value(const  ::rss_msgs::DigitalStatusMsg_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x7a2af7d23e6ef46fULL;
  static const uint64_t static_value2 = 0xbd1d9066e3666f04ULL;
};

template<class ContainerAllocator>
struct DataType< ::rss_msgs::DigitalStatusMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rss_msgs/DigitalStatusMsg";
  }

  static const char* value(const  ::rss_msgs::DigitalStatusMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rss_msgs::DigitalStatusMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool[8] slow\n\
bool[8] fast\n\
";
  }

  static const char* value(const  ::rss_msgs::DigitalStatusMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::rss_msgs::DigitalStatusMsg_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rss_msgs::DigitalStatusMsg_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.slow);
    stream.next(m.fast);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct DigitalStatusMsg_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rss_msgs::DigitalStatusMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::rss_msgs::DigitalStatusMsg_<ContainerAllocator> & v) 
  {
    s << indent << "slow[]" << std::endl;
    for (size_t i = 0; i < v.slow.size(); ++i)
    {
      s << indent << "  slow[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.slow[i]);
    }
    s << indent << "fast[]" << std::endl;
    for (size_t i = 0; i < v.fast.size(); ++i)
    {
      s << indent << "  fast[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.fast[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // RSS_MSGS_MESSAGE_DIGITALSTATUSMSG_H

