/* Auto-generated by genmsg_cpp for file /home/rss-student/RSS-I-group/rss_msgs/msg/EncoderMsg.msg */
#ifndef RSS_MSGS_MESSAGE_ENCODERMSG_H
#define RSS_MSGS_MESSAGE_ENCODERMSG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace rss_msgs
{
template <class ContainerAllocator>
struct EncoderMsg_ {
  typedef EncoderMsg_<ContainerAllocator> Type;

  EncoderMsg_()
  : left(0)
  , right(0)
  {
  }

  EncoderMsg_(const ContainerAllocator& _alloc)
  : left(0)
  , right(0)
  {
  }

  typedef int64_t _left_type;
  int64_t left;

  typedef int64_t _right_type;
  int64_t right;


private:
  static const char* __s_getDataType_() { return "rss_msgs/EncoderMsg"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "10ec03ad83d596042691890fad8ead6e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int64 left\n\
int64 right\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, left);
    ros::serialization::serialize(stream, right);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, left);
    ros::serialization::deserialize(stream, right);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(left);
    size += ros::serialization::serializationLength(right);
    return size;
  }

  typedef boost::shared_ptr< ::rss_msgs::EncoderMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rss_msgs::EncoderMsg_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct EncoderMsg
typedef  ::rss_msgs::EncoderMsg_<std::allocator<void> > EncoderMsg;

typedef boost::shared_ptr< ::rss_msgs::EncoderMsg> EncoderMsgPtr;
typedef boost::shared_ptr< ::rss_msgs::EncoderMsg const> EncoderMsgConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::rss_msgs::EncoderMsg_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::rss_msgs::EncoderMsg_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace rss_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rss_msgs::EncoderMsg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rss_msgs::EncoderMsg_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rss_msgs::EncoderMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "10ec03ad83d596042691890fad8ead6e";
  }

  static const char* value(const  ::rss_msgs::EncoderMsg_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x10ec03ad83d59604ULL;
  static const uint64_t static_value2 = 0x2691890fad8ead6eULL;
};

template<class ContainerAllocator>
struct DataType< ::rss_msgs::EncoderMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rss_msgs/EncoderMsg";
  }

  static const char* value(const  ::rss_msgs::EncoderMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rss_msgs::EncoderMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64 left\n\
int64 right\n\
";
  }

  static const char* value(const  ::rss_msgs::EncoderMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::rss_msgs::EncoderMsg_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rss_msgs::EncoderMsg_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.left);
    stream.next(m.right);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct EncoderMsg_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rss_msgs::EncoderMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::rss_msgs::EncoderMsg_<ContainerAllocator> & v) 
  {
    s << indent << "left: ";
    Printer<int64_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<int64_t>::stream(s, indent + "  ", v.right);
  }
};


} // namespace message_operations
} // namespace ros

#endif // RSS_MSGS_MESSAGE_ENCODERMSG_H

