/* Auto-generated by genmsg_cpp for file /home/rss-student/RSS-I-group/rss_msgs/msg/MotionMsg.msg */
#ifndef RSS_MSGS_MESSAGE_MOTIONMSG_H
#define RSS_MSGS_MESSAGE_MOTIONMSG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace rss_msgs
{
template <class ContainerAllocator>
struct MotionMsg_ {
  typedef MotionMsg_<ContainerAllocator> Type;

  MotionMsg_()
  : translationalVelocity(0.0)
  , rotationalVelocity(0.0)
  {
  }

  MotionMsg_(const ContainerAllocator& _alloc)
  : translationalVelocity(0.0)
  , rotationalVelocity(0.0)
  {
  }

  typedef double _translationalVelocity_type;
  double translationalVelocity;

  typedef double _rotationalVelocity_type;
  double rotationalVelocity;


private:
  static const char* __s_getDataType_() { return "rss_msgs/MotionMsg"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "dcd1efab7b0193f9e7f726b14abbf015"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 translationalVelocity\n\
float64 rotationalVelocity\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, translationalVelocity);
    ros::serialization::serialize(stream, rotationalVelocity);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, translationalVelocity);
    ros::serialization::deserialize(stream, rotationalVelocity);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(translationalVelocity);
    size += ros::serialization::serializationLength(rotationalVelocity);
    return size;
  }

  typedef boost::shared_ptr< ::rss_msgs::MotionMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rss_msgs::MotionMsg_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MotionMsg
typedef  ::rss_msgs::MotionMsg_<std::allocator<void> > MotionMsg;

typedef boost::shared_ptr< ::rss_msgs::MotionMsg> MotionMsgPtr;
typedef boost::shared_ptr< ::rss_msgs::MotionMsg const> MotionMsgConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::rss_msgs::MotionMsg_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::rss_msgs::MotionMsg_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace rss_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rss_msgs::MotionMsg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rss_msgs::MotionMsg_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rss_msgs::MotionMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dcd1efab7b0193f9e7f726b14abbf015";
  }

  static const char* value(const  ::rss_msgs::MotionMsg_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xdcd1efab7b0193f9ULL;
  static const uint64_t static_value2 = 0xe7f726b14abbf015ULL;
};

template<class ContainerAllocator>
struct DataType< ::rss_msgs::MotionMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rss_msgs/MotionMsg";
  }

  static const char* value(const  ::rss_msgs::MotionMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rss_msgs::MotionMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 translationalVelocity\n\
float64 rotationalVelocity\n\
";
  }

  static const char* value(const  ::rss_msgs::MotionMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::rss_msgs::MotionMsg_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rss_msgs::MotionMsg_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.translationalVelocity);
    stream.next(m.rotationalVelocity);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MotionMsg_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rss_msgs::MotionMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::rss_msgs::MotionMsg_<ContainerAllocator> & v) 
  {
    s << indent << "translationalVelocity: ";
    Printer<double>::stream(s, indent + "  ", v.translationalVelocity);
    s << indent << "rotationalVelocity: ";
    Printer<double>::stream(s, indent + "  ", v.rotationalVelocity);
  }
};


} // namespace message_operations
} // namespace ros

#endif // RSS_MSGS_MESSAGE_MOTIONMSG_H

