/* Auto-generated by genmsg_cpp for file /home/rss-student/RSS-I-group/rss_msgs/msg/SonarMsg.msg */
#ifndef RSS_MSGS_MESSAGE_SONARMSG_H
#define RSS_MSGS_MESSAGE_SONARMSG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace rss_msgs
{
template <class ContainerAllocator>
struct SonarMsg_ {
  typedef SonarMsg_<ContainerAllocator> Type;

  SonarMsg_()
  : range(0.0)
  , isFront(false)
  {
  }

  SonarMsg_(const ContainerAllocator& _alloc)
  : range(0.0)
  , isFront(false)
  {
  }

  typedef double _range_type;
  double range;

  typedef uint8_t _isFront_type;
  uint8_t isFront;


private:
  static const char* __s_getDataType_() { return "rss_msgs/SonarMsg"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "bca27647dbedaf9bc9f2f5ef58a241bc"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 range\n\
bool isFront\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, range);
    ros::serialization::serialize(stream, isFront);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, range);
    ros::serialization::deserialize(stream, isFront);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(range);
    size += ros::serialization::serializationLength(isFront);
    return size;
  }

  typedef boost::shared_ptr< ::rss_msgs::SonarMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rss_msgs::SonarMsg_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SonarMsg
typedef  ::rss_msgs::SonarMsg_<std::allocator<void> > SonarMsg;

typedef boost::shared_ptr< ::rss_msgs::SonarMsg> SonarMsgPtr;
typedef boost::shared_ptr< ::rss_msgs::SonarMsg const> SonarMsgConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::rss_msgs::SonarMsg_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::rss_msgs::SonarMsg_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace rss_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rss_msgs::SonarMsg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rss_msgs::SonarMsg_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rss_msgs::SonarMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bca27647dbedaf9bc9f2f5ef58a241bc";
  }

  static const char* value(const  ::rss_msgs::SonarMsg_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xbca27647dbedaf9bULL;
  static const uint64_t static_value2 = 0xc9f2f5ef58a241bcULL;
};

template<class ContainerAllocator>
struct DataType< ::rss_msgs::SonarMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rss_msgs/SonarMsg";
  }

  static const char* value(const  ::rss_msgs::SonarMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rss_msgs::SonarMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 range\n\
bool isFront\n\
";
  }

  static const char* value(const  ::rss_msgs::SonarMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::rss_msgs::SonarMsg_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rss_msgs::SonarMsg_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.range);
    stream.next(m.isFront);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SonarMsg_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rss_msgs::SonarMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::rss_msgs::SonarMsg_<ContainerAllocator> & v) 
  {
    s << indent << "range: ";
    Printer<double>::stream(s, indent + "  ", v.range);
    s << indent << "isFront: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isFront);
  }
};


} // namespace message_operations
} // namespace ros

#endif // RSS_MSGS_MESSAGE_SONARMSG_H

