/* Auto-generated by genmsg_cpp for file /home/rss-student/RSS-I-group/lab5_msgs/msg/GUILineMsg.msg */
#ifndef LAB5_MSGS_MESSAGE_GUILINEMSG_H
#define LAB5_MSGS_MESSAGE_GUILINEMSG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "lab5_msgs/ColorMsg.h"

namespace lab5_msgs
{
template <class ContainerAllocator>
struct GUILineMsg_ {
  typedef GUILineMsg_<ContainerAllocator> Type;

  GUILineMsg_()
  : lineA(0.0)
  , lineB(0.0)
  , lineC(0.0)
  , color()
  {
  }

  GUILineMsg_(const ContainerAllocator& _alloc)
  : lineA(0.0)
  , lineB(0.0)
  , lineC(0.0)
  , color(_alloc)
  {
  }

  typedef double _lineA_type;
  double lineA;

  typedef double _lineB_type;
  double lineB;

  typedef double _lineC_type;
  double lineC;

  typedef  ::lab5_msgs::ColorMsg_<ContainerAllocator>  _color_type;
   ::lab5_msgs::ColorMsg_<ContainerAllocator>  color;


private:
  static const char* __s_getDataType_() { return "lab5_msgs/GUILineMsg"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "5ee858aa33ac4230e8ab893c71e571e8"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 lineA\n\
float64 lineB\n\
float64 lineC\n\
ColorMsg color\n\
================================================================================\n\
MSG: lab5_msgs/ColorMsg\n\
int64 r\n\
int64 g\n\
int64 b\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, lineA);
    ros::serialization::serialize(stream, lineB);
    ros::serialization::serialize(stream, lineC);
    ros::serialization::serialize(stream, color);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, lineA);
    ros::serialization::deserialize(stream, lineB);
    ros::serialization::deserialize(stream, lineC);
    ros::serialization::deserialize(stream, color);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(lineA);
    size += ros::serialization::serializationLength(lineB);
    size += ros::serialization::serializationLength(lineC);
    size += ros::serialization::serializationLength(color);
    return size;
  }

  typedef boost::shared_ptr< ::lab5_msgs::GUILineMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab5_msgs::GUILineMsg_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GUILineMsg
typedef  ::lab5_msgs::GUILineMsg_<std::allocator<void> > GUILineMsg;

typedef boost::shared_ptr< ::lab5_msgs::GUILineMsg> GUILineMsgPtr;
typedef boost::shared_ptr< ::lab5_msgs::GUILineMsg const> GUILineMsgConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::lab5_msgs::GUILineMsg_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::lab5_msgs::GUILineMsg_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace lab5_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::lab5_msgs::GUILineMsg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::lab5_msgs::GUILineMsg_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::lab5_msgs::GUILineMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5ee858aa33ac4230e8ab893c71e571e8";
  }

  static const char* value(const  ::lab5_msgs::GUILineMsg_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5ee858aa33ac4230ULL;
  static const uint64_t static_value2 = 0xe8ab893c71e571e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::lab5_msgs::GUILineMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "lab5_msgs/GUILineMsg";
  }

  static const char* value(const  ::lab5_msgs::GUILineMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::lab5_msgs::GUILineMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 lineA\n\
float64 lineB\n\
float64 lineC\n\
ColorMsg color\n\
================================================================================\n\
MSG: lab5_msgs/ColorMsg\n\
int64 r\n\
int64 g\n\
int64 b\n\
";
  }

  static const char* value(const  ::lab5_msgs::GUILineMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::lab5_msgs::GUILineMsg_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::lab5_msgs::GUILineMsg_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.lineA);
    stream.next(m.lineB);
    stream.next(m.lineC);
    stream.next(m.color);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GUILineMsg_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab5_msgs::GUILineMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::lab5_msgs::GUILineMsg_<ContainerAllocator> & v) 
  {
    s << indent << "lineA: ";
    Printer<double>::stream(s, indent + "  ", v.lineA);
    s << indent << "lineB: ";
    Printer<double>::stream(s, indent + "  ", v.lineB);
    s << indent << "lineC: ";
    Printer<double>::stream(s, indent + "  ", v.lineC);
    s << indent << "color: ";
s << std::endl;
    Printer< ::lab5_msgs::ColorMsg_<ContainerAllocator> >::stream(s, indent + "  ", v.color);
  }
};


} // namespace message_operations
} // namespace ros

#endif // LAB5_MSGS_MESSAGE_GUILINEMSG_H

