/* Auto-generated by genmsg_cpp for file /home/rss-student/RSS-I-group/lab5_msgs/msg/GUIPointMsg.msg */
#ifndef LAB5_MSGS_MESSAGE_GUIPOINTMSG_H
#define LAB5_MSGS_MESSAGE_GUIPOINTMSG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "lab5_msgs/ColorMsg.h"

namespace lab5_msgs
{
template <class ContainerAllocator>
struct GUIPointMsg_ {
  typedef GUIPointMsg_<ContainerAllocator> Type;

  GUIPointMsg_()
  : x(0.0)
  , y(0.0)
  , shape(0)
  , color()
  {
  }

  GUIPointMsg_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , shape(0)
  , color(_alloc)
  {
  }

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef int64_t _shape_type;
  int64_t shape;

  typedef  ::lab5_msgs::ColorMsg_<ContainerAllocator>  _color_type;
   ::lab5_msgs::ColorMsg_<ContainerAllocator>  color;


private:
  static const char* __s_getDataType_() { return "lab5_msgs/GUIPointMsg"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "88fef43974ed58433a24c05c8e4d27fd"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 x\n\
float64 y\n\
int64 shape\n\
ColorMsg color\n\
================================================================================\n\
MSG: lab5_msgs/ColorMsg\n\
int64 r\n\
int64 g\n\
int64 b\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, x);
    ros::serialization::serialize(stream, y);
    ros::serialization::serialize(stream, shape);
    ros::serialization::serialize(stream, color);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, x);
    ros::serialization::deserialize(stream, y);
    ros::serialization::deserialize(stream, shape);
    ros::serialization::deserialize(stream, color);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(x);
    size += ros::serialization::serializationLength(y);
    size += ros::serialization::serializationLength(shape);
    size += ros::serialization::serializationLength(color);
    return size;
  }

  typedef boost::shared_ptr< ::lab5_msgs::GUIPointMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab5_msgs::GUIPointMsg_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GUIPointMsg
typedef  ::lab5_msgs::GUIPointMsg_<std::allocator<void> > GUIPointMsg;

typedef boost::shared_ptr< ::lab5_msgs::GUIPointMsg> GUIPointMsgPtr;
typedef boost::shared_ptr< ::lab5_msgs::GUIPointMsg const> GUIPointMsgConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::lab5_msgs::GUIPointMsg_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::lab5_msgs::GUIPointMsg_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace lab5_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::lab5_msgs::GUIPointMsg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::lab5_msgs::GUIPointMsg_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::lab5_msgs::GUIPointMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "88fef43974ed58433a24c05c8e4d27fd";
  }

  static const char* value(const  ::lab5_msgs::GUIPointMsg_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x88fef43974ed5843ULL;
  static const uint64_t static_value2 = 0x3a24c05c8e4d27fdULL;
};

template<class ContainerAllocator>
struct DataType< ::lab5_msgs::GUIPointMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "lab5_msgs/GUIPointMsg";
  }

  static const char* value(const  ::lab5_msgs::GUIPointMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::lab5_msgs::GUIPointMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 x\n\
float64 y\n\
int64 shape\n\
ColorMsg color\n\
================================================================================\n\
MSG: lab5_msgs/ColorMsg\n\
int64 r\n\
int64 g\n\
int64 b\n\
";
  }

  static const char* value(const  ::lab5_msgs::GUIPointMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::lab5_msgs::GUIPointMsg_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::lab5_msgs::GUIPointMsg_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.shape);
    stream.next(m.color);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GUIPointMsg_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab5_msgs::GUIPointMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::lab5_msgs::GUIPointMsg_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "shape: ";
    Printer<int64_t>::stream(s, indent + "  ", v.shape);
    s << indent << "color: ";
s << std::endl;
    Printer< ::lab5_msgs::ColorMsg_<ContainerAllocator> >::stream(s, indent + "  ", v.color);
  }
};


} // namespace message_operations
} // namespace ros

#endif // LAB5_MSGS_MESSAGE_GUIPOINTMSG_H

